project_rate/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from projects import views as proj_views


router = routers.DefaultRouter()
router.register(r'profiles', user_views.ProfileViewSet)
router.register(r'users', user_views.UserViewSet)
router.register(r'posts', proj_views.PostViewSet)
router.register(r'comments', proj_views.CommentViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('v1/',include(router.urls)),
    path('', include('projects.urls')),
    path('register/',user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from . import views
from django.urls import path
from .views import PostDetailView, PostCreateView, PostDeleteView, PostUpdateView


urlpatterns = [
    path('', views.index, name='welcome'),
    path('<int:post_id>/comment/', views.add_comment, name='addcomment'),
    path('post/<int:post_id>/like', views.add_like, name='like-post'),
    path('user/', views.search_user, name='search-user'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/new/', views.PostCreateView.as_view(), name='new-post'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='update-post'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete-post'),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    url = models.URLField()
    desc = models.TextField()
    image_url = models.ImageField(default='default.jpg', upload_to='project_pics')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tech_used = models.CharField(max_length=250)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk':self.pk}) 


    @classmethod
    def get_all_posts(cls):
        return cls.objects.order_by('-date_posted')


class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.content


class Rating(models.Model):
    rating_choices = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
    ]
    design = models.IntegerField(default=0, choices = rating_choices, null=True)
    usability = models.IntegerField(default=0, choices = rating_choices, null=True)
    content = models.IntegerField(default=0, choices = rating_choices, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.post.title

    @classmethod
    def get_all_ratings(cls, post_id):
        return cls.objects.filter(post_id=post_id)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
                                                                                                                                                                                                                                                                                                                                                                                                                                                    contact = models.CharField(max_length=100, null=True)
    company = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'


    def save(self, **kwargs):
        super().save()

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

   

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile
from crispy_forms.helper import FormHelper


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=150)

    class Meta:
        model = User
        fields = ['username','email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(max_length=150)


    class Meta:
        model = User
        fields = ['username','email']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)

class ProfileUpdateForm(forms.ModelForm):
    bio = forms.CharField()

    class Meta:
        model = Profile
        fields = ['image', 'bio', 'contact', 'company']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import SignUpForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from rest_framework import viewsets, permissions
from django.contrib.auth.models import User
from .models import Profile
from .serializers import ProfileSerializer, UserSerializer
from projects.models import Post

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            messages.success(request, f'Account created')
            return redirect('login')
    else:
        form = SignUpForm()
       
    return render(request, 'users/register.html',{'form': form} )


@login_required
def profile(request):
    user = request.user
    posts = Post.objects.filter(user=user.id)
    if request.method == 'POST':
        up_form = UserUpdateForm(request.POST, instance=request.user)
        pr_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if up_form.is_valid() and pr_form.is_valid():
            up_form.save()
            pr_form.save()
            messages.success(request, f'Account has been updated')
            return redirect('profile')
    else:
        up_form = UserUpdateForm(instance=request.user)
        pr_form = ProfileUpdateForm(instance=request.user.profile)
    content = {
        'user_form': up_form,
        'profile_form': pr_form,
        'posts': posts
    }
    return render(request, 'users/profile.html', content)

class ProfileViewSet(viewsets.ModelViewSet):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    # permission_classes = [permissions.IsAuthenticated]

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row">
        
        <div class="col-md-6 offset-md-3 login">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">                    
                    {{form | crispy}}    
                </div>
                <div class="form-group">
                    <button type= "submit" class="btn btn-outline-info">Log in</button>
                </div>
            </form>
            <div class="pt-3">
                <small class="text-muted">Need an account? <a href="{% url 'register'%}" class="btn btn-outline-success">Sign up</a></small>
            </div>
        </div>
        
    </div>
{% endblock %}

users/templates/users/logout.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h4>You have been logged out</h4>
            <div class="pt-3">
                <small class="text-muted">Login again <a href="{% url 'login'%}" class="btn btn-success">Login again</a></small>
            </div>
        </div>
        
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row content-section">
        <div class="col-sm-12">
            <div class="media" style="width: 40%; margin:1em auto;">
                <img src="{{user.profile.image.url}}" alt="{{user.username}}" class="account-img">
                <div class="media-body" style="margin-left: 1em;">
                    <h5 class="account-heading">{{user.username}}</h5>
                    <p class="text-secondary">{{user.email}}</p>
                    <p>{{user.profile.bio}}</p>
                    <p>{{user.profile.company}}</p>
                    <p>{{user.profile.contact}}</p>
                </div>
            </div>
            <div style="width: 80%; margin:0 auto">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <h5 class="text-danger text-center">Update Profile Info</h5>
                        {{user_form | crispy}}
                        {{profile_form | crispy}}
                    </div>
                    <div class="form-group mt-0">
                        <button type= "submit" class="btn btn-outline-info">Update</button>
                    </div>
                </form>   
            </div>
                     
        </div>
        
    </div>
    <h4 class="text-danger text-center">Projects</h4>
    <div class="row">
        
        {% for post in posts %}
            <div class="col-sm-4">

                <div class="card mt-1">
                                        
                    <img class="card-img-top mt-1" src="{{post.image_url.url}}" alt="{{post.title}}" title="{{post.url}}" style="height: 20vh;">
                    <div class="card-body">
                        
                        <div class="react">
                            <img data-toggle="collapse" data-target="#commentSec{{post.id}}" src="https://img.icons8.com/metro/26/000000/comments.png"/></a>                    

                        </div>
                        
                        <p class="card-text">{{post.desc}}</p>
                        <div class="react">
                            <p>{{post.comment_set.all | length}} Comments</p>
                        </div>                     
                    </div>
                    <div class="card-footer collapse" id='commentSec{{post.id}}'>
                            
                        {% for comment in post.comment_set.all %}
                            <small>{{comment.content}}</small><br>
                        {% endfor %}
                        
                    </div>
                </div>
            </div>
            {% endfor %}
    </div>
    
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row">       
        <div class="col-md-6 offset-md-3 register">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <h4 class="mb-4">Register</h4>
                    {{form | crispy}}
    
                </div>
                <div class="form-group">
                    <button type= "submit" class="btn btn-outline-info">Create account</button>
                </div>
            </form>
            <div class="pt-3">
                <small class="text-muted">Already have an account? <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a></small>
            </div>
        </div>
        
    </div>
{% endblock %}